INSERT INTO ROOM (NAME,ROOM_NUMBER,BED_INFO) VALUES ('Piccadilly', 'P1', '1');
INSERT INTO ROOM (NAME,ROOM_NUMBER,BED_INFO) VALUES ('Piccadilly', 'P2', '2');
INSERT INTO ROOM (NAME,ROOM_NUMBER,BED_INFO) VALUES ('Cambridge', 'C1', '3');
INSERT INTO ROOM (NAME,ROOM_NUMBER,BED_INFO) VALUES ('Cambridge', 'C2', '4');
INSERT INTO ROOM (NAME,ROOM_NUMBER,BED_INFO) VALUES ('Westminster', 'W1', '5');
INSERT INTO ROOM (NAME,ROOM_NUMBER,BED_INFO) VALUES ('Westminster', 'W2', '6');